/** Shared London boroughs + regional coverage for keywords & structured data */

export const LONDON_BOROUGHS = [
  "City of London",
  "Barking and Dagenham",
  "Barnet",
  "Bexley",
  "Brent",
  "Bromley",
  "Camden",
  "Croydon",
  "Ealing",
  "Enfield",
  "Greenwich",
  "Hackney",
  "Hammersmith and Fulham",
  "Haringey",
  "Harrow",
  "Havering",
  "Hillingdon",
  "Hounslow",
  "Islington",
  "Kensington and Chelsea",
  "Kingston upon Thames",
  "Lambeth",
  "Lewisham",
  "Merton",
  "Newham",
  "Redbridge",
  "Richmond upon Thames",
  "Southwark",
  "Sutton",
  "Tower Hamlets",
  "Waltham Forest",
  "Wandsworth",
  "Westminster",
] as const

export const HOME_COUNTIES_AND_REGIONS = [
  "Kent",
  "Essex",
  "Surrey",
  "Hertfordshire",
  "Berkshire",
  "Buckinghamshire",
  "East Sussex",
  "West Sussex",
  "Bedfordshire",
  "Hampshire",
  "Oxfordshire",
  "Cambridgeshire",
] as const
